[tool.poetry]
name = "pyside6-quickstart"
version = "0.1.0"
description = ""
authors = ["reshdesu"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
